std_msgs/Header header

float32 effective_rear_overhang # [m] Effective rear overhang (i.e. dist. middle trailer axle to rear trailer)
float32 length_trailer # [m] Length (semi-)trailer
float32 kingpin_setback # [m] Kingpin setback (i.e. dist. kingpin to front trailer)
float32 wheel_base_trailer # [m] Wheel base (semi-)trailer (i.e. distance kingpin to middle trailer axles)
float32 width_trailer # [m] Width (semi-)trailer
